// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqzfniovwuwnfygmwhru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxemZuaW92d3V3bmZ5Z213aHJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMDc4MjUsImV4cCI6MjA1OTU4MzgyNX0.Fy5LqxRgf1fAa4U7YHLmDLTbivakhS7Iwpiwi6h69vg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);